/**
 * Creating a sidebar for History.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  historySidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  historySidebar: [
    'intro',
    {
      type: 'category',
      label: '中国历史',
      items: ['china/ancient', 'china/modern'],
    },
    {
      type: 'category',
      label: '世界历史',
      items: ['world/ancient', 'world/modern'],
    },
  ],
   */
};

export default sidebars;
